/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TecnologiaTechRouteImport } from './routes/tecnologia.$tech'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnologiaTechRoute = TecnologiaTechRouteImport.update({
  id: '/tecnologia/$tech',
  path: '/tecnologia/$tech',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tecnologia/$tech': typeof TecnologiaTechRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tecnologia/$tech': typeof TecnologiaTechRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tecnologia/$tech': typeof TecnologiaTechRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tecnologia/$tech'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tecnologia/$tech'
  id: '__root__' | '/' | '/tecnologia/$tech'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TecnologiaTechRoute: typeof TecnologiaTechRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnologia/$tech': {
      id: '/tecnologia/$tech'
      path: '/tecnologia/$tech'
      fullPath: '/tecnologia/$tech'
      preLoaderRoute: typeof TecnologiaTechRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TecnologiaTechRoute: TecnologiaTechRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
